### PR TITLE
Events preview

### PR DESCRIPTION
**Pull request by franalderete7**

### CODE REVIEW

**Comment by franalderete7** [comment]
Added date and location as an initial preview. Let me know if it looks good please.

**Comment by closerearth** [comment]
I think this needs a bit more styling. Could you check in with Bea to have it designed?

**Comment by franalderete7** [comment]
Yesss !

**Comment by b-triz** [comment]
@samueldelesque can you check this out?

**Review by closerearth — APPROVED** [review]

**Pull request merged**
