### PR TITLE
Members Tagline

### PR DESCRIPTION
**Pull request by franalderete7**

### CODE REVIEW

**Comment by closerearth** [comment]
Let's move the user description under the timezone

**Comment by closerearth** [comment]
Let's move the user description under the timezone

**Comment by b-triz** [comment]
tagline removed, can merge @samueldelesque @closerearth

**Comment by b-triz** [comment]
@franalderete7  will put on trello, but can you follow up with @closerearth  and move user description to be aligned with name and time zone/location?

**Comment by b-triz** [comment]
@closerearth ready to merge

**Review by closerearth — APPROVED** [review]

**Pull request merged**
