### PR TITLE
Global string function

### PR DESCRIPTION
**Pull request by franalderete7**

### CODE REVIEW

**Comment by franalderete7** [comment]
Going through 'components' folder from top to bottom.

**Comment by franalderete7** [comment]
How is base.json looking?

**Comment by closerearth** [comment]
Awesome thank you!

**Review by closerearth — APPROVED** [review]

**Comment by closerearth** [comment]
There are still plenty of strings to be wrapped - but I can merge this one already and you can keep going in the next MR :)

**Pull request merged**
