### PR TITLE
Members social links

### PR DESCRIPTION
**Pull request by franalderete7**
Edit and delete functionalities

### CODE REVIEW

**Comment by closerearth** [comment]
Some changes:
- use icon TiDelete next to the link in grey color (black on hover), and let's get rid of the trash icon toggle and just always show the remove button.
- change the add icon to be a `btn` with text "add" - but create a new `btn-small` class to make it smaller. Align the button to the right.
- remove all those flex-col that are unecessary (and make the component fit the width of the column
-  "Add social link" can be moved to strings file, and "cancel" too (you can make that `generic_cancel` - let's re-use this kind of generic strings).
- saving should not reload page
- the method you wanna use is `platform.user.findOne` (not find)

**Comment by b-triz** [comment]
@franalderete7 not working fran:
- links do not disappear when I press the arrow
- modifications altered events designs

**Comment by closerearth** [comment]
Error: Cannot read properties of undefined (reading 'links')

**Comment by closerearth** [comment]
Why did you revert?
We don't want this trash icon toggle thing - it's a confusing experience. Just have the link to delete the link appear on hover.

**Comment by closerearth** [comment]
The delete button still doesn't work...

**Comment by closerearth** [comment]
- add link modal should close on successful submit
- on error, show the error in a error box in the modal

**Comment by b-triz** [comment]
sup here?

**Comment by b-triz** [comment]
@samueldelesque @closerearth @franalderete7  ping ping

**Comment by closerearth** [comment]
- I shouldn't see the delete link button on other peoples profiles.
- the delete link should only show on hover.

**Comment by closerearth** [comment]
Looks good!

**Pull request merged**
